### ISSUE TITLE
django-hijack 3.0.0 is not compatible with latest release tag (2.1.10)

### ISSUE THREAD

**Issue by umarmughal824** [django-hijack/django-hijack-admin#46]
While integrating it with Django==3.2, I started to get error because the settings files have been remove from django and put in conf.py

```
Traceback (most recent call last):

  File "/src/manage.py", line 19, in <module>

    execute_from_command_line(sys.argv)

  File "/home/mitodl/.local/lib/python3.9/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line

    utility.execute()

  File "/home/mitodl/.local/lib/python3.9/site-packages/django/core/management/__init__.py", line 395, in execute

    django.setup()

  File "/home/mitodl/.local/lib/python3.9/site-packages/django/__init__.py", line 24, in setup

    apps.populate(settings.INSTALLED_APPS)

  File "/home/mitodl/.local/lib/python3.9/site-packages/django/apps/registry.py", line 122, in populate

    app_config.ready()

  File "/home/mitodl/.local/lib/python3.9/site-packages/django/contrib/admin/apps.py", line 27, in ready

    self.module.autodiscover()

  File "/home/mitodl/.local/lib/python3.9/site-packages/django/contrib/admin/__init__.py", line 24, in autodiscover

    autodiscover_modules('admin', register_to=site)

  File "/home/mitodl/.local/lib/python3.9/site-packages/django/utils/module_loading.py", line 47, in autodiscover_modules

    import_module('%s.%s' % (app_config.name, module_to_search))

  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module

    return _bootstrap._gcd_import(name[level:], package, level)

  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import

  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load

  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked

  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked

  File "<frozen importlib._bootstrap_external>", line 850, in exec_module

  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed

  File "/src/users/admin.py", line 5, in <module>

    from hijack_admin.admin import HijackUserAdminMixin

  File "/usr/local/lib/python3.9/site-packages/hijack_admin/admin.py", line 9, in <module>

    from hijack import settings as hijack_settings

ImportError: cannot import name 'settings' from 'hijack' (/home/mitodl/.local/lib/python3.9/site-packages/hijack/__init__.py)
```

**Comment by powderflask** [comment]
Confirmed. Suggest title: "django-hijack-admin release tag 2.1.10 not compatible with django-hijack v. 3.x"

`hijack_admin.admin` contains this import statement:
`from hijack import settings as hijack_settings`

But `hijack.settings` no longer exists.

I'd be happy to have a crack at updating hijack_admin for compatibility with hijack V.3.x  if no one else is already at that task?

**Comment by mosesmc52** [comment]
Will anyone be fixing this bug?
