### ISSUE TITLE
Unable to install with last setuptools >= 59.*

### ISSUE THREAD

**Issue by submarcos** [django-hijack/django-hijack-admin#48]
Since last setuptools update, it's not possible to install this package from pypi

```bash
pip install setuptools==59.* -U
pip install django-hijack-admin
```

results with: 

```bash
  ERROR: Command errored out with exit status 1:
   command: /venv/bin/python3.8 -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-iqo9p33i/django-hijack-admin_a859a87cbd2f4200962a3694363865ee/setup.py'"'"'; __file__='"'"'/tmp/pip-install-iqo9p33i/django-hijack-admin_a859a87cbd2f4200962a3694363865ee/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-zmkhj6_1
       cwd: /tmp/pip-install-iqo9p33i/django-hijack-admin_a859a87cbd2f4200962a3694363865ee/
  Complete output (26 lines):
  running egg_info
  creating /tmp/pip-pip-egg-info-zmkhj6_1/django_hijack_admin.egg-info
  writing /tmp/pip-pip-egg-info-zmkhj6_1/django_hijack_admin.egg-info/PKG-INFO
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-install-iqo9p33i/django-hijack-admin_a859a87cbd2f4200962a3694363865ee/setup.py", line 44, in <module>
      setup(name="django-hijack-admin",
    File "/venv/lib/python3.8/site-packages/setuptools/__init__.py", line 153, in setup
      return distutils.core.setup(**attrs)
    File "/usr/lib/python3.8/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/usr/lib/python3.8/distutils/dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/venv/lib/python3.8/site-packages/setuptools/command/egg_info.py", line 292, in run
      writer(self, ep.name, os.path.join(self.egg_info, ep.name))
    File "/venv/lib/python3.8/site-packages/setuptools/command/egg_info.py", line 656, in write_pkg_info
      metadata.write_pkg_info(cmd.egg_info)
    File "/usr/lib/python3.8/distutils/dist.py", line 1117, in write_pkg_info
      self.write_pkg_file(pkg_info)
    File "/venv/lib/python3.8/site-packages/setuptools/dist.py", line 167, in write_pkg_file
      write_field('Summary', single_line(self.get_description()))
    File "/venv/lib/python3.8/site-packages/setuptools/dist.py", line 151, in single_line
      raise ValueError('Newlines are not allowed')
  ValueError: Newlines are not allowed
  ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/32/24/1dc0728d7de4a9cfde85bddccaca7cc789677de8a2958e78a5484dce89ce/django-hijack-admin-2.1.10.tar.gz#sha256=330f9be331ada831248c9cee5a21202aea70fb9911b443249ce4c28d57d9e2e3 (from https://pypi.org/simple/django-hijack-admin/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Could not find a version that satisfies the requirement django-hijack-admin==2.1.10 (from versions: 2.1.0, 2.1.1, 2.1.2, 2.1.3, 2.1.4, 2.1.5, 2.1.6, 2.1.7, 2.1.8, 2.1.9, 2.1.10)
ERROR: No matching distribution found for django-hijack-admin==2.1.10
```

No problem with setuptools 58.*

Tested with python 3.8

**Comment by submarcos** [comment]
https://github.com/django-hijack/django-hijack-admin/pull/47
